name: Checks

on:
  pull_request:
    branches: [main]

jobs:
  run-checks:
    name: Run checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Install dependencies
        run: npm ci --no-audit --prefer-offline
        env:
          npm_config_fund: 'false'
          npm_config_progress: 'false'
          HUSKY: '0'

      - name: Check formatting
        run: npx prettier@$(node -p "require('./package.json').devDependencies['prettier']") --check .
