name: Dependabot Auto Merge
on: pull_request

permissions:
  pull-requests: write

jobs:
  auto-merge:
    name: Auto merge
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    steps:
      # Fetch the Dependabot metadata
      - name: Download Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      # Check if the update is a minor or patch version
      - name: Check for auto merge
        id: check-auto-merge
        run: |
          echo "approveAndMerge=$([[ '${{ steps.metadata.outputs.update-type }}' == 'version-update:semver-patch' || '${{ steps.metadata.outputs.update-type }}' == 'version-update:semver-minor' ]])" >> $GITHUB_ENV

      - name: Debug GITHUB_ENV
        run: cat $GITHUB_ENV

      # Approve the pull request
      - name: Approve pull request
        if: env.approveAndMerge == 'true'
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          github-token: ${{ secrets.DEPENDABOT_PAT }}

      # Add a comment to have Dependabot squash and merge the PR
      - name: Dependabot squash and merge
        if: env.approveAndMerge == 'true'
        run: gh pr comment ${{ github.event.pull_request.html_url }} --body "@dependabot squash and merge"
        env:
          github-token: ${{ secrets.DEPENDABOT_PAT }}
