name: Release

on:
  push:
    branches:
      - main

jobs:
  # Uses sematic-release to create release notes
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Get all history for tags
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: npm ci --no-audit --prefer-offline --ignore-scripts --include=dev

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_PAT }}
        run: npx semantic-release
